#!/sbin/busybox sh
# This is script is only usefull to dual-boot CM10.2 and B2G.

cd /

busybox mount -t proc proc /proc
busybox mount -t sysfs sysfs /sys

if grep -q bootmode=2 /proc/cmdline ; then
  cp -a /res/misc/init.40/* /
  cp -a /recovery.rc /init.rc
  exec /sbin/init2
fi
if busybox grep -q 1 /sys/class/power_supply/battery/batt_lp_charging ; then
  # low power mode
  cp -a /res/misc/init.40/* /
  cp lpm.rc init.rc
  rm init.smdk4210.rc
  chmod 755 /innt
  chmod 644 /*.rc
  chmod 644 /*.prop
  exec /sbin/init2
fi

mkdir -p /dev/block
mkdir /dev/input
mkdir /dev/graphics
mknod /dev/graphics/fb0 c 29 0
mknod /dev/input/event1 c 13 65
mknod /dev/input/event2 c 13 66
mknod /dev/input/event8 c 13 72
mknod /dev/input/event9 c 13 73
mknod /dev/ashmem c 10 61
mknod /dev/block/mmcblk0p7 b 179 7
mknod /dev/block/mmcblk0p9 b 259 1
mknod /dev/block/mmcblk0p10 b 259 2
mknod /dev/block/mmcblk0p11 b 259 3
mknod /dev/block/mmcblk0p12 b 259 4
mknod /dev/block/loop0 b 7 0

mkdir -p /mnt
chmod 755 /mnt
mkdir /preload
mount -t ext4 -o ro /dev/block/mmcblk0p12 /preload
mount -t vfat /dev/block/mmcblk0p11 /mnt

SECONDROM=1
[ -f /preload/build.prop ] || SECONDROM=0

DEFAULTROM=`cat /mnt/.defaultrom`

umount /preload
umount /mnt

if [ "$DEFAULTROM" == "1" ]; then
  SECONDROM=0
fi

if [ "$SECONDROM" == "0" ]; then
  #CYANOGENMOD
  mount -t ext4 /dev/block/mmcblk0p9 /system
else
  #B2G
  mount -t ext4 /dev/block/mmcblk0p12 /system
fi

mv -f /sbin/adbd.jb /sbin/adbd

B2G=1
[ -d /system/b2g ] || B2G=0

if [ "$B2G" == "1" ]; then
    cp -a /res/misc/init.b2g/* /
    #We don't insmod anything in init.rc for the time being (b2g)
    insmod /lib/modules/Si4709_driver.ko
 else
    mv -f /res/misc/init.cm10.2/* /
    mv -f /lib/modules/*.ko /system/lib/modules
fi

rm -rf /vendor

umount /system
rm -rf /res/misc/init*
chmod 755 /innt
chmod 644 /*.rc
chmod 644 /*.prop
chmod -R 755 /lib

exec /sbin/init2
